{{- range $stsName, $sts := .Values.statefulSets }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $stsName }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- include "sts.labels" ( dict "commonLabels" $.Values.commonLabels "context" $ ) | indent 2 }}
  {{- include "sts.annotations" ( dict "commonAnnotations" $.Values.commonAnnotations "context" $ ) | indent 2 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
  serviceName: {{ include "sts.serviceName" ( dict "Release" $.Release "stsName" $stsName ) }}
  replicas: {{ default 1 $sts.replicas }}
  template:
    metadata:
      {{- include "pod.labels" ( dict "podLabels" $sts.podLabels "context" $ ) | indent 6 }}
      {{- include "pod.annotations" ( dict "podLabels" $sts.podAnnotations "context" $ ) | indent 6 }}
    spec:
      {{- include "pod.serviceAccountName" ( dict "serviceAccountName" $sts.serviceAccountName "context" $) | indent 6 }}
      {{- include "pod.nodeSelector" ( dict "nodeSelector" $sts.nodeSelector "context" $ ) | indent 6 }}
      {{- include "pod.affinity" ( dict "affinity" $sts.affinity "context" $ ) | indent 6 }}
      {{- include "pod.tolerations" ( dict "tolerations" $sts.tolerations "context" $ ) | indent 6 }}
      {{- include "pod.volumes" ( dict "volumes" $sts.volumes "context" $ ) | indent 6 }}
      {{- include "pod.initContainers" ( dict "initContainers" $sts.initContainers ) | indent 6 }}
      {{- include "pod.containers" ( dict "containers" $sts.containers ) | indent 6 }}
  {{- include "sts.vcts" ( dict "vcts" $sts.vcts "context" $ ) | indent 2 }}
{{- end }}
